version: '3'

services:
  apache2:
    image: httpd:latest    
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
      - ./apache:/usr/local/apache2/conf
    restart: always

